export const participant1Mazes = {
  set1Practice1: {
    id: "set1Practice1",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "coop", "tap", "coop", "tape",
      "tape", "cup", "tape", "tap",
      "tap", "cup", "coop", "tape",
      "cup", "coop", "tap", "cup",
    ],
    truePath: [
      {"row":3,"col":4},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":2,"col":2},
      {"row":1,"col":2},
      {"row":0,"col":2},
    ],
    labeledCells: [
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":2,"col":3},
      {"row":3,"col":3},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":363,"left":505,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":-20,"left":240,"transform":"translate(-50%, 0)"},
    ],
  },
  set1Practice2: {
    id: "set1Practice2",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "tape", "coop", "tap", "tape",
      "cup", "tape", "cup", "coop",
      "tap", "coop", "tap", "cup",
      "cup", "tape", "coop", "tap",
    ],
    truePath: [
      {"row":1,"col":4},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":2,"col":2},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":0},
    ],
    labeledCells: [
      {"row":0,"col":2},
      {"row":1,"col":2},
      {"row":0,"col":3},
      {"row":1,"col":3},
    ],
    prompt: "Are you ready to start practice 2?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":124,"left":505,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":340,"left":0,"transform":"translate(-50%, 0)"},
    ],
  },
  set1Practice3: {
    id: "set1Practice3",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "tape", "cup", "tape", "cup",
      "coop", "tap", "coop", "tape",
      "tap", "cup", "coop", "tap",
      "coop", "tape", "tape", "cup",
    ],
    truePath: [
      {"row":3,"col":0},
      {"row":3,"col":1},
      {"row":3,"col":2},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":2,"col":2},
      {"row":1,"col":2},
      {"row":1,"col":1},
      {"row":0,"col":1},
    ],
    labeledCells: [
      {"row":2,"col":0},
      {"row":3,"col":0},
      {"row":2,"col":1},
      {"row":3,"col":1},
    ],
    prompt: "Are you ready to start practice 3?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":363,"left":-20,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":-20,"left":120,"transform":"translate(-50%, 0)"},
    ],
  },
  set1Test1: {
    id: "set1Test1",
    mode: "giver",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "tape", "cup", "tape", "tape", "tap", "coop",
      "tap", "coop", "tap", "cup", "tape", "cup",
      "cup", "tape", "coop", "coop", "coop", "tape",
      "tap", "tape", "coop", "tape", "coop", "tap",
      "coop", "cup", "tap", "cup", "tap", "tape",
      "cup", "coop", "cup", "tape", "coop", "cup",
    ],
    truePath: [
      {"row":5,"col":6},
      {"row":5,"col":5},
      {"row":5,"col":4},
      {"row":4,"col":4},
      {"row":4,"col":3},
      {"row":4,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":1},
      {"row":2,"col":1},
      {"row":1,"col":1},
      {"row":1,"col":2},
      {"row":1,"col":3},
      {"row":2,"col":3},
      {"row":2,"col":4},
      {"row":2,"col":5},
      {"row":1,"col":5},
      {"row":0,"col":5},
    ],
    labeledCells: [
      {"row":4,"col":4},
      {"row":4,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":5},
    ],
    prompt: "Are you ready to start test 1?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":503.5,"left":625,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":0,"left":500,"transform":"translate(-50%, -50%)"},
    ],
  },
  set1Test2: {
    id: "set1Test2",
    mode: "giver",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "tap", "cup", "coop", "cup", "coop", "coop",
      "coop", "tape", "tape", "tape", "tap", "cup",
      "tap", "cup", "tap", "coop", "cup", "tap",
      "coop", "tape", "cup", "tape", "tape", "coop",
      "cup", "tape", "tap", "coop", "tape", "cup",
      "tape", "coop", "cup", "tap", "cup", "tap",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":4},
      {"row":2,"col":4},
      {"row":3,"col":4},
      {"row":3,"col":3},
      {"row":4,"col":3},
      {"row":5,"col":3},
      {"row":5,"col":4},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":3,"col":5},
      {"row":3,"col":6},
    ],
    labeledCells: [
      {"row":0,"col":0},
      {"row":0,"col":1},
      {"row":1,"col":0},
      {"row":1,"col":1},
    ],
    prompt: "Are you ready to start test 2?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":102.5,"left":-22,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":304.5,"left":600,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Practice1: {
    id: "set2Practice1",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "coop", "tape", "coop", "tape",
      "tap", "cup", "tap", "cup",
      "coop", "tape", "coop", "tape",
      "tap", "cup", "tap", "cup",
    ],
    truePath: [
      {"row":2,"col":4},
      {"row":2,"col":3},
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":1},
      {"row":2,"col":1},
      {"row":1,"col":1},
      {"row":0,"col":1},
    ],
    labeledCells: [
      {"row":1,"col":2},
      {"row":2,"col":2},
      {"row":1,"col":3},
      {"row":2,"col":3},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":243,"left":505,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Practice2: {
    id: "set2Practice2",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "coop", "tap", "coop", "tap",
      "tape", "cup", "tape", "cup",
      "coop", "tap", "coop", "tap",
      "tape", "cup", "tape", "cup",
    ],
    truePath: [
      {"row":3,"col":4},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":1},
      {"row":2,"col":1},
      {"row":1,"col":1},
      {"row":1,"col":0},
    ],
    labeledCells: [
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":2,"col":3},
      {"row":3,"col":3},
    ],
    prompt: "Are you ready to start practice 2?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":363,"left":505,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Practice3: {
    id: "set2Practice3",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tap", "coop", "tap",
      "tape", "coop", "tape", "coop",
      "cup", "tap", "cup", "tap",
      "tape", "coop", "tape", "cup",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":2},
      {"row":2,"col":2},
      {"row":2,"col":3},
      {"row":2,"col":4},
    ],
    labeledCells: [
      {"row":0,"col":0},
      {"row":1,"col":0},
      {"row":0,"col":1},
      {"row":1,"col":1},
    ],
    prompt: "Are you ready to start practice 3?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":123,"left":-25,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Test1: {
    id: "set2Test1",
    mode: "drawer",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "cup", "tap", "tape", "coop", "tap", "coop",
      "coop", "tape", "tap", "tape", "cup", "tape",
      "tap", "cup", "tap", "coop", "tap", "coop",
      "coop", "tape", "coop", "cup", "cup", "tape",
      "cup", "tap", "tap", "tape", "tap", "coop",
      "tape", "coop", "cup", "coop", "cup", "tape",
    ],
    truePath: [
      {"row":0,"col":1},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":4,"col":2},
      {"row":4,"col":3},
      {"row":5,"col":3},
      {"row":5,"col":4},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":3,"col":5},
      {"row":3,"col":4},
      {"row":2,"col":4},
      {"row":1,"col":4},
      {"row":1,"col":5},
      {"row":1,"col":6},
    ],
    labeledCells: [
      {"row":0,"col":0},
      {"row":0,"col":1},
      {"row":1,"col":0},
      {"row":1,"col":1},
    ],
    prompt: "Are you ready to start test 1?",
    markers: [
      {"role":"start","image":"/images/startup.png","top":-20,"left":100,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Test2: {
    id: "set2Test2",
    mode: "drawer",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "tap", "cup", "tap", "cup", "tape", "coop",
      "coop", "tape", "coop", "tape", "coop", "tap",
      "tap", "cup", "coop", "tap", "coop", "tape",
      "tape", "cup", "tape", "cup", "tap", "coop",
      "tap", "tap", "coop", "tape", "coop", "tape",
      "cup", "tape", "tape", "cup", "tap", "cup",
    ],
    truePath: [
      {"row":5,"col":6},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":4,"col":4},
      {"row":4,"col":3},
      {"row":5,"col":3},
      {"row":5,"col":2},
      {"row":4,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":0},
    ],
    labeledCells: [
      {"row":4,"col":4},
      {"row":4,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":5},
    ],
    prompt: "Are you ready to start test 2?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":500,"left":625,"transform":"translate(-50%, -50%)"},
    ],
  },
};

export const participant2Mazes = {
  set1Practice1: {
    id: "set1Practice1",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tap", "tape", "coop",
      "tape", "coop", "tap", "cup",
      "cup", "tape", "cup", "tape",
      "coop", "tap", "coop", "tap",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":4,"col":2},
    ],
    labeledCells: [
      {"row":0,"col":0},
      {"row":1,"col":0},
      {"row":0,"col":1},
      {"row":1,"col":1},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":123,"left":-20,"transform":"translate(-50%, -50%)"},
    ],
  },
  set1Practice2: {
    id: "set1Practice2",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tap", "tape", "cup",
      "cup", "coop", "coop", "tap",
      "coop", "cup", "tape", "tape",
      "tape", "tap", "coop", "tap",
    ],
    truePath: [
      {"row":3,"col":0},
      {"row":3,"col":1},
      {"row":3,"col":2},
      {"row":2,"col":2},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":4},
    ],
    labeledCells: [
      {"row":2,"col":0},
      {"row":3,"col":0},
      {"row":2,"col":1},
      {"row":3,"col":1},
    ],
    prompt: "Are you ready to start practice 2?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":363,"left":-20,"transform":"translate(-50%, -50%)"},
    ],
  },
  set1Practice3: {
    id: "set1Practice3",
    mode: "drawer",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tape", "tape", "coop",
      "tap", "coop", "cup", "tap",
      "cup", "coop", "tap", "coop",
      "tap", "tape", "cup", "tape",
    ],
    truePath: [
      {"row":1,"col":4},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":3},
      {"row":4,"col":3},
    ],
    labeledCells: [
      {"row":0,"col":2},
      {"row":1,"col":2},
      {"row":0,"col":3},
      {"row":1,"col":3},
    ],
    prompt: "Are you ready to start practice 3?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":123,"left":503,"transform":"translate(-50%, -50%)"},
    ],
  },
  set1Test1: {
    id: "set1Test1",
    mode: "drawer",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "cup", "coop", "tape", "cup", "coop", "cup",
      "tape", "tap", "cup", "tap", "cup", "coop",
      "tap", "coop", "tape", "coop", "tape", "tap",
      "tap", "coop", "coop", "coop", "tape", "cup",
      "cup", "tape", "cup", "tap", "coop", "tap",
      "coop", "tap", "tape", "tape", "cup", "tape",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":1,"col":2},
      {"row":2,"col":2},
      {"row":2,"col":3},
      {"row":2,"col":4},
      {"row":3,"col":4},
      {"row":3,"col":5},
      {"row":4,"col":5},
      {"row":5,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":3},
      {"row":4,"col":3},
      {"row":4,"col":2},
      {"row":4,"col":1},
      {"row":5,"col":1},
      {"row":6,"col":1},
    ],
    labeledCells: [
      {"row":0,"col":0},
      {"row":0,"col":1},
      {"row":1,"col":0},
      {"row":1,"col":1},
    ],
    prompt: "Are you ready to start test 1?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":103,"left":-20,"transform":"translate(-50%, -50%)"},
    ],
  },
  set1Test2: {
    id: "set1Test2",
    mode: "drawer",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "tap", "cup", "tap", "cup", "tape", "tape",
      "cup", "tape", "coop", "tap", "coop", "cup",
      "coop", "tape", "tape", "cup", "tape", "coop",
      "tap", "cup", "coop", "tap", "cup", "tap",
      "cup", "tap", "tape", "tape", "tape", "coop",
      "coop", "coop", "cup", "coop", "cup", "tap",
    ],
    truePath: [
      {"row":5,"col":6},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":4,"col":4},
      {"row":4,"col":3},
      {"row":5,"col":3},
      {"row":5,"col":2},
      {"row":4,"col":2},
      {"row":3,"col":2},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":0},
    ],
    labeledCells: [
      {"row":4,"col":4},
      {"row":4,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":5},
    ],
    prompt: "Are you ready to start test 2?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":503,"left":625,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Practice1: {
    id: "set2Practice1",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tap", "cup", "tap",
      "tape", "coop", "tape", "coop",
      "cup", "tap", "cup", "tap",
      "tape", "coop", "tape", "coop",
    ],
    truePath: [
      {"row":2,"col":0},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":1,"col":2},
      {"row":1,"col":3},
      {"row":2,"col":3},
      {"row":3,"col":3},
      {"row":4,"col":3},
    ],
    labeledCells: [
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":2,"col":3},
      {"row":3,"col":3},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":242,"left":-20,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":460,"left":360,"transform":"translate(-50%, 0)"},
    ],
  },
  set2Practice2: {
    id: "set2Practice2",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tape", "cup", "tape",
      "tap", "coop", "tap", "coop",
      "cup", "tape", "cup", "tape",
      "tap", "coop", "tap", "coop",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":2},
      {"row":2,"col":2},
      {"row":1,"col":2},
      {"row":1,"col":3},
      {"row":2,"col":3},
      {"row":3,"col":3},
      {"row":3,"col":4},
    ],
    labeledCells: [
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":2,"col":3},
      {"row":3,"col":3},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/end.png","top":363,"left":482,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/startleft.png","top":98,"left":-20,"transform":"translate(-50%, 0)"},
    ],
  },
  set2Practice3: {
    id: "set2Practice3",
    mode: "giver",
    timed: false,
    cellSize: 120,
    gridSize: 4,
    items: [
      "cup", "tape", "coop", "tape",
      "tap", "cup", "tap", "cup",
      "coop", "tape", "coop", "tape",
      "tap", "coop", "tap", "cup",
    ],
    truePath: [
      {"row":3,"col":4},
      {"row":3,"col":3},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":2,"col":2},
      {"row":2,"col":1},
      {"row":2,"col":0},
    ],
    labeledCells: [
      {"row":2,"col":2},
      {"row":3,"col":2},
      {"row":2,"col":3},
      {"row":3,"col":3},
    ],
    prompt: "Are you ready to start practice 1?",
    markers: [
      {"role":"start","image":"/images/startright.png","top":363,"left":505,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":220,"left":0,"transform":"translate(-50%, 0)"},
    ],
  },
  set2Test1: {
    id: "set2Test1",
    mode: "giver",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "tape", "cup", "coop", "cup", "coop", "tape",
      "coop", "tap", "tape", "tap", "tap", "cup",
      "tape", "cup", "cup", "coop", "tape", "coop",
      "coop", "tap", "coop", "tap", "cup", "tap",
      "tape", "cup", "tape", "tap", "tape", "coop",
      "coop", "tap", "coop", "tape", "tap", "cup",
    ],
    truePath: [
      {"row":6,"col":5},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":4,"col":4},
      {"row":3,"col":4},
      {"row":2,"col":4},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":2},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":3,"col":1},
      {"row":3,"col":2},
      {"row":4,"col":2},
      {"row":5,"col":2},
      {"row":5,"col":1},
      {"row":5,"col":0},
    ],
    labeledCells: [
      {"row":4,"col":4},
      {"row":4,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":5},
    ],
    prompt: "Are you ready to start test 1?",
    markers: [
      {"role":"start","image":"/images/startdown.png","top":629,"left":500,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":507.5,"left":0,"transform":"translate(-50%, -50%)"},
    ],
  },
  set2Test2: {
    id: "set2Test2",
    mode: "giver",
    timed: true,
    cellSize: 100,
    gridSize: 6,
    items: [
      "cup", "tap", "cup", "tape", "cup", "tape",
      "tape", "coop", "tape", "coop", "tap", "tap",
      "coop", "tap", "cup", "tape", "cup", "tape",
      "tape", "coop", "tap", "coop", "cup", "tap",
      "tap", "coop", "tape", "coop", "tape", "coop",
      "coop", "tape", "cup", "tap", "cup", "tap",
    ],
    truePath: [
      {"row":1,"col":0},
      {"row":1,"col":1},
      {"row":2,"col":1},
      {"row":2,"col":2},
      {"row":2,"col":3},
      {"row":1,"col":3},
      {"row":1,"col":4},
      {"row":2,"col":4},
      {"row":3,"col":4},
      {"row":3,"col":3},
      {"row":4,"col":3},
      {"row":5,"col":3},
      {"row":5,"col":4},
      {"row":5,"col":5},
      {"row":4,"col":5},
      {"row":3,"col":5},
      {"row":3,"col":6},
    ],
    labeledCells: [
      {"row":4,"col":4},
      {"row":4,"col":5},
      {"row":5,"col":4},
      {"row":5,"col":5},
    ],
    prompt: "Are you ready to start test 1?",
    markers: [
      {"role":"start","image":"/images/startleft.png","top":103.5,"left":-20,"transform":"translate(-50%, -50%)"},
      {"role":"end","image":"/images/end.png","top":304.5,"left":600,"transform":"translate(-50%, -50%)"},
    ],
  },
};
